databases:
  - name: job_webapp
    plan: free
    databaseName: job_webapp
    user: enesbarut

services:
  - type: web
    plan: free
    name: job_aggregator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn job_aggregator.asgi:application --host 0.0.0.0 --port 10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job_webapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4