databases:
  - name: job_webapp
    plan: free
    databaseName: job_webapp
    user: enesbarut

services:
  - type: web
    plan: free
    name: job_aggregator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn job_aggregator.asgi:application -k uvicorn.workers.UvicornWorker -b 0.0.0.0:10000"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job_webapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: job_aggregator.settings