databases:
  - name: job_webapp
    plan: free
    databaseName: job_webapp
    user: enesbarut

services:
  - type: web
    plan: free
    name: job_aggregator
    runtime: python
    buildCommand: "./job_aggregator/build.sh"
    startCommand: "python -m gunicorn job_aggregator.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job_webapp
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4