# Generated by Django 4.2.10 on 2024-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0003_alter_resetforgottenpassword_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetforgottenpassword",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
